### ISSUE TITLE
Custom types with collection properties do not work

### ISSUE THREAD

**Issue by ksuszka** [adrianaisemberg/CLAP#11]
Hi

With CLAP 3.8 downloaded from nuget I'm not able to run sample from http://adrianaisemberg.github.com/CLAP/#custom_types site. I get TypeConvertionException.

It seems that there is a problem with deserializing a list of nested objects like PhoneNumbers in this example.

**Comment by ksuszka** [comment]
Quick tests with previous CLAP versions show that it was broken in CLAP 3.5. It did work in CLAP 3.4.1.0.

**Comment by adrianaisemberg** [comment]
Interesting. I'll check it ASAP.

Thanks!

Adrian Aisemberg
vercue.com http://www.vercue.com
sharpregion.com http://www.sharpregion.com

On Tue, Mar 20, 2012 at 2:25 PM, ksuszka <
reply@reply.github.com

**Comment by adrianaisemberg** [comment]
Fixed in 3.9.
The problem was that when trying to validate custom types, it was trying to get values of indexer properties, and failing.
Fixed by skipping indexer properties.
