### ISSUE TITLE
Writing RunConsole Errors to Console.Error instead of Console.Out

### ISSUE THREAD

**Issue by ralfkret** [adrianaisemberg/CLAP#16]
Seems like CLAP writes the message of an exception to the Console.Out stream when using RunConsole. So when you redirect the output to a file the error message will end up in that file. It would be nicer if you would write the message to Console.Error instead.

Anyway: I great library! LOVE IT!

r

**Comment by adrianaisemberg** [comment]
True.
Will be fixed!

**Comment by ralfkret** [comment]
Priceless!
Tia
Ralf
Am 04.05.2012 01:36 schrieb "Adrian Aisemberg" <
reply@reply.github.com

**Comment by adrianaisemberg** [comment]
fixed
