### ISSUE TITLE
Default verb is ignored

### ISSUE THREAD

**Issue by hickford** [adrianaisemberg/CLAP#17]
Hi. `Verb(IsDefault=true)` doesn't work. When I run my program without args, I still get the help message

```
$ ExampleProject.exe

  exercise|e (Default): Build a tree 
          /labelname        : target variable (String)
```

**Comment by adrianaisemberg** [comment]
Well, it seems like a fresh bug. Thanks!
Do you use Run or RunConsole ?

**Comment by hickford** [comment]
RunConsole. Yes I think this bug is fresh since the exit codes change.

**Comment by adrianaisemberg** [comment]
I see.
It happens because RunConsole() automatically defines a [Help, Empty] handler.
Until I fix this, you can use Run().

**Comment by adrianaisemberg** [comment]
Fixed.
Single parsers don't have a registered empty help handler when using RunConsole.
Multi-parser still have those.

**Comment by hickford** [comment]
Thanks Adrian
