### ISSUE TITLE
Support for Enum Flags?

### ISSUE THREAD

**Issue by halwaxt** [adrianaisemberg/CLAP#19]
First I want to thank you for your great work!

Is there a way to provide enum parameters which are defined as flags and or'ed together?

```
[Flags]
enum FileType {
    Csv,
    Excel
}

[Verb]
void CreateFiles([Parameter] FileType fileType) { ... }
```

How to call the method with Csv and Excel enabled?

```
MySuperApp createfiles -filetype=Csv|Excel
```

Thanks in advance
Thomas

**Comment by adrianaisemberg** [comment]
Interesting!
Currently you'll have to parse it by yourself but it's a great feature.
I'll implement.

Thanks,
Adrian

[mobile]
From: halwaxt
Sent: 6/8/2012 1:52 PM
To: Adrian Aisemberg
Subject: [CLAP] Support for Enum Flags? (#19)
First I want to thank you for your great work!

Is there a way to provide enum parameters which are defined as flags
and or'ed together?

```
[Flags]
enum FileType {
    Csv,
    Excel
}

[Verb]
void CreateFiles([Parameter] FileType fileType) { ... }
```

How to call the method with Csv and Excel enabled?

```
MySuperApp createfiles -filetype=Csv|Excel
```

Thanks in advance
Thomas

---

Reply to this email directly or view it on GitHub:
https://github.com/adrianaisemberg/CLAP/issues/19

**Comment by adrianaisemberg** [comment]
Apparently, flag enums are already supported using a comma:
MySuperApp createfiles -filetype=Csv,Excel

That's how Enum.Parse works, which is used by CLAP.

Cheers!

**Comment by adrianaisemberg** [comment]
Don't forget to set a proper flag value to each enum value:

[Flags]
enum FileType
{
    Csv = 1,
    Excel = 2,
    ...4, 8, 16 ...
}

otherwise, the compiler will set the default values, which are 0,1,2,3,... which are not real flags.

**Comment by halwaxt** [comment]
Thanks for your help Adrian, I'll implement your suggestions as soon as possible!

Thomas

**Comment by halwaxt** [comment]
Adrian,

works like a charm :-) Thanks a lot!

Thomas
