### ISSUE TITLE
Localizing description strings

### ISSUE THREAD

**Issue by brutaldev** [adrianaisemberg/CLAP#26]
I really want to be able to use a resource key instead of having the language specific string for Description directly in the attribute. I would normally just use a trick similar to this example: http://stackoverflow.com/a/17381168/564726

Unfortunately the Global and Verb attributes are sealed and description is not virtual so you cannot inherit from it and dynamically return a description string.

Could I please request that the attributes that contain properties that could be localized (Description in both VerbAttribute and GlobalAttribute) be unsealed and the localizable properties be made virtual so that developers can customize how the string is retrieved?

**Comment by brutaldev** [comment]
Another argument in favour of this is that parameters should now use DescriptionAttribute (since description in ParameterAttribute is obsolete which allows them to be easily localized by inheriting from DescriptionAttribute and overriding the Description getter. You cannot do the same for Verb and Global.

**Comment by adrianaisemberg** [comment]
Hi,

It is all open-source. You can freely make any changes you want and send me
for review. I'd be happy to push the changes into the main branch and
release a new version.

Thanks,
Adrian

Adrian Aisemberg
vercue.com http://www.vercue.com
sharpregion.com http://www.sharpregion.com

**Comment by brutaldev** [comment]
Changes were merged in and released with 4.5.
