### ISSUE TITLE
Merge #24 break when an exception is not serializable

### ISSUE THREAD

**Issue by MrJingle** [adrianaisemberg/CLAP#30]
Hi,
in the latest version (3.5.2) of autofac, to support the PCL the author(Nicholas Blumhardt) removed the SerializableAttribute(and the associated constructor) from the DependecyResolutionException class.
(https://github.com/autofac/Autofac/commit/1db4ee417e16ea878953041a54a9b2b33b8d30f1, file Core/Source/Autofac/Core/DependencyResolutionException.cs)
The merge [https://github.com/adrianaisemberg/CLAP/pull/24] will cause Clap to fail when trying to serialize such exception.
There should be some conditional checking and maybe a fallback on the old behavior if the exception is not serializable.

Thanks,
MrJingle

**Comment by adrianaisemberg** [comment]
As a quick workaround, I suggest wrapping this line:

```
PreserveStackTrace(tex.InnerException);
```

With an empty try-catch

**Comment by adrianaisemberg** [comment]
Committed. Nugetted.
