### ISSUE TITLE
Allow [DirectoryExists], [FileExists], [PathExists] to be applied to global parameters

### ISSUE THREAD

**Issue by rossipedia** [adrianaisemberg/CLAP#32]
I'd like to expose a global parameter that is essentially a data directory.

I'm trying to do something like:

``` c#
[Global("d")]
[DirectoryExists]
public void DataDir(string dir)
{
    this.dataDir = dir;
}
```

But, of course I can't because the `DirectoryExistsAttribute` is marked with `[AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter)]`

It would be very helpful to allow these validation attributes on global parameters

**Comment by adrianaisemberg** [comment]
I agree. Please send me a pull request with the changes and please make
sure there are unit tests that cover this new feature.

Thanks,
Adrian

**Comment by rossipedia** [comment]
For sure. I've forked the repo and set up a branch, I'll try to dig in sometime over the next couple of days.

**Comment by adrianaisemberg** [comment]
Cheers!
