### ISSUE TITLE
Strong name assemblies

### ISSUE THREAD

**Issue by csxpjc** [adrianaisemberg/CLAP#38]
CLAP dlls should be strong named to enable consumers of those assemblies to strong name themselves. When strong naming at build time all referenced dlls must also be strong named, if they are not then the consumer cannot be strong named as it would break the chain.

https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx

**Comment by csxpjc** [comment]
I am of course referring to the compiled binaries here: https://github.com/adrianaisemberg/CLAP/downloads

I can of course download the source and build and strong name it myself, which I think I am going to do anyway as I've just noticed the compiled binaries are rather old.

**Comment by adrianaisemberg** [comment]
Agree.

Thanks,
Adrian

Adrian Aisemberg

Get Tapet for Android
https://play.google.com/store/apps/details?id=com.sharpregion.tapet

**Comment by FlorianAsal** [comment]
Pls just sign the assemblies. Managing it by NuGet is much easier than doing all that lazy stuff manually.
