### ISSUE TITLE
Add support for Argument Models

### ISSUE THREAD

**Issue by clmcgrath** [adrianaisemberg/CLAP#44]
please add support for arguments models , 
most CLI frameworks are supporting this via Property attributes, 
this increases code reuse and makes the code look much cleaner 
i like everything about his framework except this aspect 
some of the applications i create are quite large CLI programs for development and deployment tooling this is the only thing stopping me from using this for our larger projects ,  as the verb method signatures quickly get very messy and unruly with more then a few verb arguments

**Comment by clmcgrath** [comment]
I saw that you do support custom types but only as json/xml input ,  while this is helpful for my needs does not solve my primary issue

**Comment by adrianaisemberg** [comment]
Thanks for your feedback. Appreciated!
Unfortunately I have no plans on adding new features but as this is an open-source project we can hope someone will pick this up.

**Comment by clmcgrath** [comment]
Guess I will be moving on then...
