### ISSUE TITLE
Feature Request: Interactive REPL shell support

### ISSUE THREAD

**Issue by ByronScottJones** [adrianaisemberg/CLAP#45]
Some command line tools, such as NETSH and NSLOOKUP allow you to provide command line parameters and receive an immediate response, but they also support an interactive mode, where you call the command without parameters, and it then displays an interactive shell.  It seems to me that adding this capability to CLAP would be fairly straightforward. Is this something you would be interested in doing, or should I look at doing it as a fork? It seems that extending the Parser.Run method to support an interactive mode would do the trick.

**Comment by adrianaisemberg** [comment]
Neat idea.
As I no longer actively work on this project, feel free to implement it and I'll be happy to merge to main.

Regards,
Adrian
