### ISSUE TITLE
Simpler scenarios support

### ISSUE THREAD

**Issue by The-Futurist** [adrianaisemberg/CLAP#46]
Hi,
This looks cool but seems to require the developer perceive their app as being invoked:

`application.exe <verb> <args>`

Is it possible to use CLAP in a minimal way allowing simple:

`application.exe <args>`

The flexibility and generality is excellent but forcing that pattern for simple app's seems overkill.

**Comment by adrianaisemberg** [comment]
A verb can be marked as IsDefault, which I believe will answer your question.
Please let me know if it helps.

```
        [Verb(IsDefault = true)]
        static void foo()
        {

        }

```
