### ISSUE TITLE
Assembly contains references to .NET 3.5 where it should only reference .NET 2.0

### ISSUE THREAD

**Issue by honekamp** [adrianaisemberg/CLAP#9]
The download available from https://github.com/downloads/adrianaisemberg/CLAP/CLAP.FW2.v3.2.zip contains references to .NET 3.5 assemblies and therefore does not compile in a project that targets .NET 2.0.

When using NuGet for fetching CLAP the following problem is reported (most likely the reason is similar):

`Successfully installed 'CLAP 3.3'.
Successfully uninstalled 'CLAP 3.3'.
Install failed. Rolling back...
Could not install package 'CLAP 3.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v2.0', but the package does not contain any assembly references that are compatible with that framework. For more information, contact the package author.`

**Comment by adrianaisemberg** [comment]
Interesting. I'll check it.
Thanks for noticing.

**Comment by adrianaisemberg** [comment]
Hi,

The new version of CLAP indeed requires some .NET 3.5 assemblies (for JSON
deserialization).
I will remove the 2.0 downloadable from the list.
I will also consider creating a lighter version which doesn't support JSON.

Thanks,
Adrian

Adrian Aisemberg
vercue.com http://www.vercue.com
sharpregion.com http://www.sharpregion.com

On Mon, Dec 5, 2011 at 4:43 PM, honekamp <
reply@reply.github.com

**Comment by adrianaisemberg** [comment]
The new version of CLAP indeed requires some .NET 3.5 assemblies (for JSON deserialization).
I will remove the 2.0 downloadable from the list.
I will also consider creating a lighter version which doesn't support JSON.

**Comment by adrianaisemberg** [comment]
This issue is fixed in v3.4.
JSON is not supported when using the .NET Framework v2.0 version of CLAP.

**Comment by honekamp** [comment]
Thanks, Adrian.

I'll give it a try as soon as possible.
